[[redirects]]
  from = "/workshop"
  to = "/workshop.html"
  status = 200

[[redirects]]
  from = "/join-group"
  to = "/join-group.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
